### ISSUE TITLE
While trying to calculate Tribhagi Dasa(New Feature),will adding the dasaperiod for planet work?

### ISSUE THREAD

**Issue by sushiljic** [erajasekar/Astrosoft#10]
While trying to calculate Tribhagi Dasa(New Feature),will adding the dasaperiod for planet work?
i have also changed the total length by 80 rather than 120(for vimshottari dasha).

**Comment by erajasekar** [comment]
Simply changing dasaperiod/total length won't work. You need to implement Tribhagi Dasa calculation.

**Comment by sushiljic** [comment]
It is so nice to share that 
adding tribhagi dasa period and on calculating period on Dasa class.
`return ((parent.getPeriod() * lord.tribhagiDasaPeriod()) / 80);`
where tribhagiDasaPeriod are resp tribhagiDasaperiod of Planets.
