### ISSUE TITLE
Ephe file doesnot seems to open

### ISSUE THREAD

**Issue by sushiljic** [erajasekar/Astrosoft#11]
I thought  that ephe file is being opened from classpath of project but suddenly,
i found it failed to open ephe file and Mosphier ephe is being used.
Below is attached screenshot
![screenshot from 2019-03-02 19-32-03](https://user-images.githubusercontent.com/5524563/53683650-735eee00-3d2b-11e9-9ec6-8ba4a9f67e4f.png)

Can you let me know how can i have load ephe file from my project?

**Comment by erajasekar** [comment]
Refer to the documentation http://www.th-mack.de/download/swisseph-doc/swisseph/SwissEph.html#SwissEph(java.lang.String) . You will need to pass the correct path to Eph files in SwissEph constructor. But I have seen planetary positions to be accurate without eph files, so you mostly don't need it.
