### ISSUE TITLE
There are rendering errors in Fonts Exporting Horoscope to PDF in tamil using FOP 

### ISSUE THREAD

**Issue by saravanan1480** [erajasekar/Astrosoft#14]
Dear Sir,
    I am using your software frequently.Thank you Sir.
I am a newbie to Java and I ran the software where everything goes fine.I modified export directory files , especially XSL files to support Tamil  while exporting to PDF.
<img width="326" alt="Annotation 2019-10-18 151235" src="https://user-images.githubusercontent.com/36417565/67084037-d5d10580-f1b9-11e9-8fae-3c5daac8a2f7.png">

There are rendering errors in Fonts Exporting Horoscope to PDF in Tamil using FOP.
**For tamil letter 'jo' ja comes first and then supporting vowel ,but both should be embedded.**

Please help me solve this issue. I will be grateful to you.

**Are there any other options to export Horoscopes to PDF in Tamil other than Fop.**

I also need to know whether the current software supports it.

Thanks and Regards
**Saravanan N**

**Comment by saravanan1480** [comment]
Dear Sir,
 **I have found that recent FOP v 2.3 solves my problem.But I am unable to upgrade  to fop 2.3.** I am getting the following error.  I have included XMLGRAPHICS COMMONS .JAR (recent one) in lib directory.
I am getting the following error:
![Annotation 2019-10-24 183125](https://user-images.githubusercontent.com/36417565/67487999-98beb480-f68c-11e9-9b5f-fb9c9705b8b9.png)

I am unable to solve it.It is saying No such method Error : 
 **org.apache.xmlgraphics.util.Service.providerNames(Ljava/lang/Class;)Ljava/util/Iterator;**

Please provide me a solution. I will be grateful to you sir...

Thanks and Regards
**Saravanan N**

**Comment by saravanan1480** [comment]
Dear Sir,
I have solved my problem with fop.
Thank you Sir

**Comment by kavitha770** [comment]
How to install this software to my wordpress. Pls advice

**Comment by erajasekar** [comment]
You can't install it on WordPress. But you can install the software on your desktop or laptop. Please see this video https://www.youtube.com/watch?v=MbzYURTO0sc for instructions. Comment on the video if you need help.
