### ISSUE TITLE
How to calculate the rasi end on daily panchang?

### ISSUE THREAD

**Issue by sushiljic** [erajasekar/Astrosoft#7]
Hi @erajasekar 
I would like to thank you for open sourcing Astrosoft project and 
I am happy i get to know many things from it.
Now I would like to know how we can calculate the rasi end time?

For example
If on date (31th Dec,2018),Rasi is Thula.
Now i need to know when Thula will end?
I would be very helpful if you can provide me some idea?

**Comment by erajasekar** [comment]
Sushil,

You can use TransitHelper (https://github.com/erajasekar/Astrosoft/blob/master/src/app/astrosoft/util/TransitHelper.java) to find the time when Moon reaches the position 180 deg (for Thula). See how it is used in Panchag (https://github.com/erajasekar/Astrosoft/blob/master/src/app/astrosoft/core/Panchang.java#L149) to calculate Nakshathra end.

**Comment by sushiljic** [comment]
Hi @erajasekar 
Thank you for the solution and It really help me.
Now i am trying to get start date on Rasi.
I tried with 150 deg  but it give date in future
So could also help me how can i find or let me know if i need to create another thread since this can be helpful for others in future too.

**Comment by erajasekar** [comment]
Sushil,

TransitHelper will calculates time of transit starting from `startJDUT` parameter you pass to `getTransit()` method. So to look for past, just day or so from current date when calculating `startJDUT`. For e.g I subtract 2 days from current date for Muhurtha calculation (See https://github.com/erajasekar/Astrosoft/blob/master/src/app/astrosoft/core/Muhurtha.java#L57)

**Comment by sushiljic** [comment]
@erajasekar 
Thank you so much.
This solve my problem.
