### ISSUE TITLE
How to find the start day of thithi?

### ISSUE THREAD

**Issue by sushiljic** [erajasekar/Astrosoft#8]
For calculating Bhadra yog,I need to get half time of thithi so for that i need to get start time of thithi.
@erajasekar 
Let me know if you can provide me any hint.
Thank you in advance.

**Comment by erajasekar** [comment]
Finding start time of thithi should be very similar to calculating end. But the end time previous thithi will already give you start time of current thithi. So based on order of thithi's you can easily find starttime from end time of thithi.

**Comment by sushiljic** [comment]
I have tried the second approach,
Tracing the end time of previous thithi,i go to the previous day but i got into problems like
case 1. Some day, there might be elapse of thithi for eg
on 20th Dec,2018, current thithi is Thraiyodasi and its previous thithi must be Dwadasi but on sunrise,
it has Ekadasi.
case 2. Some time thithi can elongate upto 2 days, for that i might go back to again one day.
Below is the working code that i perform to find the thithi start.
But i thought if there would be some easy way to find start of thithi that would be very helpful.


        /*
        * calculate thithi starting date
        * */
        GregorianCalendar calStepperForDayBefore = (GregorianCalendar) currentDate.clone();
        while(panchangAtSunrise.getThithi().getStarting() == 0d){

            calStepperForDayBefore.add(Calendar.DAY_OF_MONTH,-1);
            calStepperForDayBefore = AstroUtil.atHourMinuteSecond(
                    calStepperForDayBefore,
                    AstroUtil.getSunRise(calStepperForDayBefore,place),
                    false);

            Panchang panAtDayBefore = new Panchang(calStepperForDayBefore,person);

            if( panchangAtSunrise.getThithi().getThithi().getPreviousThithi() == panAtDayBefore.getThithi().getThithi() ){
                panchangAtSunrise.getThithi().setStarting(panAtDayBefore.getThithi().getEnding());
                panchangAtSunrise.getThithi().setStartingDate(panAtDayBefore.getThithi().getEndingDate());
            }
            else if(panchangAtSunrise.getThithi().getThithi().getPreviousThithi().getPreviousThithi() == panAtDayBefore.getThithi().getThithi()){
                // on DayBefore, there was two thithi
                // find panchang at end of that thithi
                double atDayBeforeAtThithiEnd = panAtDayBefore.getThithi().getEnding();
                GregorianCalendar atDayBeforeAtThithiEndCal = AstroUtil.atHourMinuteSecond(calStepperForDayBefore, atDayBeforeAtThithiEnd,true);
                Panchang panAtDayBeforeAtThithiEnd = new Panchang(
                        atDayBeforeAtThithiEndCal,
                        person);
                if(panAtDayBeforeAtThithiEnd.getThithi().getThithi() ==
                        panchangAtSunrise.getThithi().getThithi().getPreviousThithi()){
                    panchangAtSunrise.getThithi().setStarting(panAtDayBeforeAtThithiEnd.getThithi().getEnding());
                    panchangAtSunrise.getThithi().setStartingDate(panAtDayBeforeAtThithiEnd.getThithi().getEndingDate());
                }
                else{
                    System.out.println("Should never happen");
                }
            }
        }

**Comment by erajasekar** [comment]
It's been several years since I worked on this code. So I don't remember all the calculation details to comment on it. Glad that you figured out some working solution.

**Comment by sushiljic** [comment]
Okay then let me close this issue
and if any better solution come up
it will post here.
