### ISSUE TITLE
How can i calculate solar month from degee of sun and month?

### ISSUE THREAD

**Issue by sushiljic** [erajasekar/Astrosoft#9]
How can i calculate solar month from degee of sun and month?
For example i need to show
Baisakh Shukla Pakshya etc
Let me know if you have any solutions

**Comment by erajasekar** [comment]
Sorry, I am not familiar with solar month. Do you mean month of hindu
calendar? Can you elaborate? or give more examples?

Thanks,
Raja.

**Comment by sushiljic** [comment]
For example of drigpanchang
![screenshot from 2019-02-19 19-09-46](https://user-images.githubusercontent.com/5524563/53018272-0c634e80-347a-11e9-9129-9c20eab58bb7.png)
There is Purnimanta Month: Magha
So i am trying to find Magha
Usually we write
Magha Shukla Paksha
If you have any idea let me know

**Comment by erajasekar** [comment]
Ok. Looks like from this article
https://en.wikipedia.org/wiki/Hindu_calendar#Amanta,_Purnimanta_systems you
will able to calculate it based on sun/moon positions. Give it a try, if
you are stuck I will see If I can help.

**Comment by sushiljic** [comment]
I have used this way,
If diff between sun and moon is greater than 180,
index of month will be (integer value of sun/30) + 1
else (integer value of sun/30)
where month are Baisakh,Jestha resp.
